"use client";

import { useEffect, useState } from "react";
import { Logo } from "./Logo";
import { SiteFooter } from "./SiteFooter";
import { destinationFromPrompt, interpretFallback } from "@/lib/request";

type Detail = { request: { destination: string; raw_prompt: string; timing: string; max_total_minor: number; status: string; required_constraints: string[]; preferred_constraints: string[] }; offers: Array<{ id: string; merchant_name: string; total_minor: number; selected: boolean; benefits: string[] }>; reservations: Array<{ id: string; merchant_name: string; status: string; booking_reference?: string }>; payments: Array<{ id: string; provider: string; status: string }> };
type HotelEnrichment = { name: string; address: string; distanceKm: number; imageUrl?: string; imageSourceUrl?: string; imageProvider?: "liteapi" | "foursquare" | "wikimedia" };
const statusLabels: Record<string, string> = { draft: "Draft", open: "Auction live", closed: "Market complete", selected: "Hotel selected", payment_pending: "Payment pending", completed: "Completed", payment_failed: "Payment failed" };

export function RequestDetail({ id }: { id: string }) {
  const [detail, setDetail] = useState<Detail | null>(null);
  const [hotels, setHotels] = useState<HotelEnrichment[]>([]);
  const [error, setError] = useState("");
  useEffect(() => { fetch(`/api/requests/${id}`).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error || "Request could not be loaded."); setDetail(body); }).catch((cause) => setError(cause.message)); }, [id]);
  useEffect(() => { if (!detail) return; const destination = destinationFromPrompt(detail.request.raw_prompt, detail.request.destination); fetch(`/api/hotels?destination=${encodeURIComponent(destination)}`).then((response) => response.json()).then((body) => { if (body.source === "geoapify" || body.source === "liteapi") setHotels(body.hotels || []); }).catch(() => undefined); }, [detail]);
  const recovered = detail ? interpretFallback(detail.request.raw_prompt) : null;
  const resumable = detail && ["draft", "open", "closed", "selected", "payment_pending"].includes(detail.request.status);
  const actionLabel = detail?.request.status === "selected" || detail?.request.status === "payment_pending" ? "Continue to payment →" : detail?.request.status === "closed" ? "Review offers →" : detail?.request.status === "draft" ? "Complete request →" : "Continue market →";
  return <main className="app-shell"><header className="topbar history-topbar"><a className="brand merchant-link" href="/"><Logo /></a><span className="kicker history-nav-label">REQUEST DETAIL</span><a className="nav-cta merchant-link" href="/history">← All requests</a></header><section className="history-page request-detail-page">{error ? <div className="history-empty"><h2>Could not open this request.</h2><p>{error}</p></div> : !detail || !recovered ? <div className="history-empty">Loading request…</div> : <><div className="detail-heading"><div className="section-heading"><span className="status-chip">{detail.request.status}</span><h1>{destinationFromPrompt(detail.request.raw_prompt, detail.request.destination)}</h1><p>{detail.request.raw_prompt}</p></div>{resumable && <a className="primary detail-continue" href={`/?resume=${id}`}>{actionLabel}</a>}</div><div className="detail-grid"><article className="card detail-card"><span className="kicker">PURCHASE MANDATE</span><dl><div><dt>When</dt><dd>{detail.request.timing}</dd></div><div><dt>Maximum total</dt><dd>{new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(recovered.maxTotalMinor / 100)}</dd></div><div><dt>Must have</dt><dd>{detail.request.required_constraints.join(" · ") || recovered.required.join(" · ") || "—"}</dd></div><div><dt>Nice to have</dt><dd>{detail.request.preferred_constraints.join(" · ") || recovered.preferred.join(" · ") || "—"}</dd></div></dl></article><article className="card detail-card"><span className="kicker">MARKET RESULT</span><h2>{detail.offers.length} offers received</h2>{detail.offers.length ? detail.offers.map((offer) => { const hotel = hotels.find((item) => item.name.toLowerCase() === offer.merchant_name.toLowerCase()); return <div className={`detail-offer ${offer.selected ? "selected" : ""}`} key={offer.id}>{hotel?.imageUrl ? <img src={hotel.imageUrl} alt={`${hotel.name} property from ${hotel.imageProvider === "foursquare" ? "Foursquare" : "Wikimedia"}`} /> : <span className="detail-hotel-fallback">{offer.merchant_name.slice(0,1)}</span>}<div><b>{offer.merchant_name}</b><small>{hotel ? `${hotel.distanceKm} km straight-line · ${hotel.address}` : offer.benefits.join(" · ")}</small></div><strong>₹{(offer.total_minor / 100).toLocaleString("en-IN")}</strong></div>; }) : <p>No offers were invited for this draft.</p>}</article></div>{hotels.length > 0 && <section className="location-card card"><div className="location-copy"><span className="kicker">SAVED MARKET MAP</span><h3>Hotels around your landmark.</h3><p>Markers and straight-line distances are refreshed from Geoapify when you open this record.</p></div><img src={`/api/hotels/map?destination=${encodeURIComponent(destinationFromPrompt(detail.request.raw_prompt, detail.request.destination))}`} alt="Map of saved hotel market" /></section>}</>}</section><SiteFooter /></main>;
}
